CREATE USER 'orangutan'@'%' IDENTIFIED BY 'orangutan';
GRANT ALL PRIVILEGES ON *.* TO 'orangutan'@'%' WITH GRANT OPTION;
FLUSH PRIVILEGES;

SET NAMES 'utf8mb4';

CREATE DATABASE library;

USE library;

-- Lookup tables (no dependencies)

CREATE TABLE genres (
    id   BIGINT NOT NULL AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL UNIQUE,
    PRIMARY KEY (id)
);

CREATE TABLE statuses (
    id   BIGINT NOT NULL AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL UNIQUE,
    PRIMARY KEY (id)
);

CREATE TABLE languages (
    id   BIGINT NOT NULL AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL UNIQUE,
    code VARCHAR(10)  NOT NULL UNIQUE,
    PRIMARY KEY (id)
);

CREATE TABLE authors (
    id   BIGINT NOT NULL AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL UNIQUE,
    PRIMARY KEY (id)
);

-- Series (no FK dependencies)

CREATE TABLE series (
    id     BIGINT NOT NULL AUTO_INCREMENT,
    name   VARCHAR(255) NOT NULL UNIQUE,
    status VARCHAR(50)  NOT NULL DEFAULT 'NOT_STARTED',  -- SeriesStatus enum: NOT_STARTED | IN_PROGRESS | COMPLETED
    PRIMARY KEY (id)
);

-- Books (depends on series)

CREATE TABLE books (
    id           BIGINT NOT NULL AUTO_INCREMENT,
    title        VARCHAR(255) NOT NULL,
    description  TEXT,
    page_count   INT,
    sort_title   VARCHAR(255),
    series_id    BIGINT,
    series_order INT,
    created_at   DATETIME,
    updated_at   DATETIME,
    PRIMARY KEY (id),
    FOREIGN KEY (series_id) REFERENCES series(id)
);

-- Book status (depends on books, statuses)

CREATE TABLE book_status (
    id         BIGINT NOT NULL AUTO_INCREMENT,
    book_id    BIGINT NOT NULL UNIQUE,
    status_id  BIGINT NOT NULL,
    started_at DATE,
    finished_at DATE,
    updated_at DATETIME,
    PRIMARY KEY (id),
    FOREIGN KEY (book_id)   REFERENCES books(id),
    FOREIGN KEY (status_id) REFERENCES statuses(id)
);

-- Reviews (depends on books)

CREATE TABLE reviews (
    id         BIGINT NOT NULL AUTO_INCREMENT,
    book_id    BIGINT NOT NULL,
    rating     SMALLINT CHECK (rating BETWEEN 1 AND 5),
    notes      TEXT,
    created_at DATETIME,
    PRIMARY KEY (id),
    FOREIGN KEY (book_id) REFERENCES books(id)
);

-- ManyToMany join tables generated by @JoinTable on Book

CREATE TABLE book_genres (
    book_id  BIGINT NOT NULL,
    genre_id BIGINT NOT NULL,
    PRIMARY KEY (book_id, genre_id),
    FOREIGN KEY (book_id)  REFERENCES books(id),
    FOREIGN KEY (genre_id) REFERENCES genres(id)
);

CREATE TABLE book_languages (
    book_id     BIGINT NOT NULL,
    language_id BIGINT NOT NULL,
    PRIMARY KEY (book_id, language_id),
    FOREIGN KEY (book_id)     REFERENCES books(id),
    FOREIGN KEY (language_id) REFERENCES languages(id)
);

CREATE TABLE book_authors (
    book_id   BIGINT NOT NULL,
    author_id BIGINT NOT NULL,
    PRIMARY KEY (book_id, author_id),
    FOREIGN KEY (book_id)   REFERENCES books(id),
    FOREIGN KEY (author_id) REFERENCES authors(id)
);


-- Gauges

CREATE TABLE gauges (
    id          BIGINT NOT NULL AUTO_INCREMENT,
    name        VARCHAR(255) NOT NULL UNIQUE,
    description TEXT,
    created_at  DATETIME NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE gauge_entries (
    id         BIGINT NOT NULL AUTO_INCREMENT,
    gauge_id   BIGINT NOT NULL,
    delta      INT NOT NULL,
    note       VARCHAR(255),
    created_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (gauge_id) REFERENCES gauges(id) ON DELETE CASCADE
);

-- Seed data for statuses

INSERT INTO statuses (name) VALUES
    ('Not Started'),
    ('In Progress'),
    ('Completed'),
    ('Did Not Finish'),
    ('Paused'),
    ('Not Applicable'),
    ('Not Interested');
