CREATE USER 'orangutan'@'%' IDENTIFIED BY 'orangutan';
GRANT ALL PRIVILEGES ON *.* TO 'orangutan'@'%' WITH GRANT OPTION;
FLUSH PRIVILEGES;

SET NAMES 'utf8mb4';

CREATE DATABASE library;

USE library;

-- Households (must come first — other tables reference this)

CREATE TABLE household (
    id         BIGINT NOT NULL AUTO_INCREMENT,
    name       VARCHAR(100) NOT NULL,
    created_at DATETIME NOT NULL,
    PRIMARY KEY (id)
);

-- User (must come second — other tables reference this)

CREATE TABLE user (
    id            BIGINT NOT NULL AUTO_INCREMENT,
    email         VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    display_name  VARCHAR(100) NOT NULL,
    role          ENUM('admin', 'user') NOT NULL DEFAULT 'user',
    household_id  BIGINT NOT NULL,
    created_at    DATETIME NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (household_id) REFERENCES household(id)
);

-- Lookup tables (no dependencies)

CREATE TABLE genre (
    id   BIGINT NOT NULL AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL UNIQUE,
    PRIMARY KEY (id)
);

CREATE TABLE tag (
    id   BIGINT NOT NULL AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL UNIQUE,
    PRIMARY KEY (id)
);

CREATE TABLE status (
    id   BIGINT NOT NULL AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL UNIQUE,
    PRIMARY KEY (id)
);

CREATE TABLE language (
    id   BIGINT NOT NULL AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL UNIQUE,
    code VARCHAR(10)  NOT NULL UNIQUE,
    PRIMARY KEY (id)
);

CREATE TABLE edition (
    id   BIGINT NOT NULL AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL UNIQUE,
    PRIMARY KEY (id)
);

-- Author (depends on household)

CREATE TABLE author (
     id           BIGINT NOT NULL AUTO_INCREMENT,
     first_name   VARCHAR(255),
     last_name    VARCHAR(255) NOT NULL,
     household_id BIGINT NOT NULL,
     PRIMARY KEY (id),
     UNIQUE KEY (household_id, last_name, first_name),
     FOREIGN KEY (household_id) REFERENCES household(id)
);

-- Series (depends on household)

CREATE TABLE series (
    id           BIGINT NOT NULL AUTO_INCREMENT,
    name         VARCHAR(255) NOT NULL,
    status       VARCHAR(50) NOT NULL DEFAULT 'NOT_STARTED',
    household_id BIGINT NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY (household_id, name),
    FOREIGN KEY (household_id) REFERENCES household(id)
);

-- Book (depends on series, household)

CREATE TABLE book (
   id           BIGINT NOT NULL AUTO_INCREMENT,
   title        VARCHAR(255) NOT NULL,
   description  TEXT,
   page_count   INT,
   year         INT,
   sort_title   VARCHAR(255),
   series_id    BIGINT,
   series_order INT,
   edition_id   BIGINT,
   household_id BIGINT NOT NULL,
   created_at   DATETIME,
   updated_at   DATETIME,
   PRIMARY KEY (id),
   FOREIGN KEY (series_id)    REFERENCES series(id),
   FOREIGN KEY (edition_id)   REFERENCES edition(id),
   FOREIGN KEY (household_id) REFERENCES household(id)
);

-- Book status (depends on books, statuses)

CREATE TABLE book_status (
    id         BIGINT NOT NULL AUTO_INCREMENT,
    book_id    BIGINT NOT NULL,
    status_id  BIGINT NOT NULL,
    user_id    BIGINT NOT NULL,
    started_at DATE,
    finished_at DATE,
    updated_at DATETIME,
    PRIMARY KEY (id),
    UNIQUE KEY (book_id, user_id),
    FOREIGN KEY (book_id)   REFERENCES book(id),
    FOREIGN KEY (status_id) REFERENCES status(id),
    FOREIGN KEY (user_id)   REFERENCES user(id)
);

-- Reviews (depends on books, users)

CREATE TABLE review (
    id         BIGINT NOT NULL AUTO_INCREMENT,
    book_id    BIGINT NOT NULL,
    user_id    BIGINT NOT NULL,
    rating     SMALLINT CHECK (rating BETWEEN 1 AND 5),
    notes      TEXT,
    created_at DATETIME,
    PRIMARY KEY (id),
    UNIQUE KEY (book_id, user_id),
    FOREIGN KEY (book_id) REFERENCES book(id),
    FOREIGN KEY (user_id) REFERENCES user(id)
);

-- ManyToMany join tables generated by @JoinTable on Book

CREATE TABLE book_genre (
    book_id  BIGINT NOT NULL,
    genre_id BIGINT NOT NULL,
    PRIMARY KEY (book_id, genre_id),
    FOREIGN KEY (book_id)  REFERENCES book(id),
    FOREIGN KEY (genre_id) REFERENCES genre(id)
);

CREATE TABLE book_tag (
     book_id  BIGINT NOT NULL,
     tag_id BIGINT NOT NULL,
     PRIMARY KEY (book_id, tag_id),
     FOREIGN KEY (book_id)  REFERENCES book(id),
     FOREIGN KEY (tag_id) REFERENCES tag(id)
);

CREATE TABLE book_language (
    book_id     BIGINT NOT NULL,
    language_id BIGINT NOT NULL,
    PRIMARY KEY (book_id, language_id),
    FOREIGN KEY (book_id)     REFERENCES book(id),
    FOREIGN KEY (language_id) REFERENCES language(id)
);

CREATE TABLE book_author (
    book_id   BIGINT NOT NULL,
    author_id BIGINT NOT NULL,
    PRIMARY KEY (book_id, author_id),
    FOREIGN KEY (book_id)   REFERENCES book(id),
    FOREIGN KEY (author_id) REFERENCES author(id)
);


-- Gauge (depends on user)

CREATE TABLE gauge (
    id          BIGINT NOT NULL AUTO_INCREMENT,
    name        VARCHAR(255) NOT NULL,
    description TEXT,
    user_id     BIGINT NOT NULL,
    created_at  DATETIME NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY (user_id, name),
    FOREIGN KEY (user_id) REFERENCES user(id)
);

CREATE TABLE gauge_entry (
    id         BIGINT NOT NULL AUTO_INCREMENT,
    gauge_id   BIGINT NOT NULL,
    delta      INT NOT NULL,
    note       VARCHAR(255),
    created_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (gauge_id) REFERENCES gauge(id) ON DELETE CASCADE
);

-- Wishlist_books (depends on household, user)

CREATE TABLE wishlist_book (
    id           BIGINT NOT NULL AUTO_INCREMENT,
    title        VARCHAR(255) NOT NULL,
    notes        TEXT,
    sort_title   VARCHAR(255),
    user_id      BIGINT NOT NULL,
    release_date DATE,
    created_at   DATETIME,
    updated_at   DATETIME,
    PRIMARY KEY (id),
    FOREIGN KEY (user_id) REFERENCES user(id)
);

CREATE TABLE wishlist_book_author (
    wishlist_book_id   BIGINT NOT NULL,
    author_id BIGINT NOT NULL,
    PRIMARY KEY (wishlist_book_id, author_id),
    FOREIGN KEY (wishlist_book_id)   REFERENCES wishlist_book(id),
    FOREIGN KEY (author_id) REFERENCES author(id)
);

-- Seed data

INSERT INTO status (name) VALUES
    ('To Be Read'),
    ('In Progress'),
    ('Completed'),
    ('Did Not Finish'),
    ('Paused'),
    ('Not Applicable'),
    ('Not Interested');

INSERT INTO language (name, code) VALUES
   ('English',  'en'),
   ('Japanese', 'ja');

INSERT INTO household (id, name, created_at) VALUES
    (1, 'Discworld', NOW()),
    (2, "Demo", NOW());

INSERT INTO user (id, email, password_hash, display_name, role, household_id, created_at) VALUES
    (1, 'orangutan@library.local', '$2b$10$7r4bDy92zEACnXzETaSqj..bLPd1XVZPUPbZDOlQ7pixludhBT53K', 'Orangutan', 'admin', 1, NOW()),
    (2, 'demo@library.local', '$2a$10$A0S6GeBsxzmPTWo3iJ6gy.PjZLheOiyyyqwLhJFR5J3K3POl.BHg6', 'Demo', 'user', 1, NOW());