version: '3.9'

services:
  # MySQL
  library-mysql:
    image: mysql:8.0
    container_name: library-mysql
    hostname: library-mysql
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - default-auth=mysql_native_password
    volumes:
      - ./mysql/boot.sql:/docker-entrypoint-initdb.d/1.sql
      - ./mysql/data.sql:/docker-entrypoint-initdb.d/2.sql
      - library-mysql-conf:/etc/mysql/conf.d
      - library-mysql-data:/var/lib/mysql
    ports:
      - "3333:3306"
    expose:
      - "3333"

volumes:
  library-mysql-conf:
  library-mysql-data:

